# vim ft=yaml
# travis-ci.org definition for DataLad build
language: python

python:
  # minium version
  - 3.5
  # "latest"
  - 3.8

cache:
  - apt

env:
  global:
    # will be used in the matrix, where neither other variable is used
    - BOTO_CONFIG=/tmp/nowhere
    - DATALAD_LOG_CMD_ENV=GIT_SSH_COMMAND
    - TESTS_TO_PERFORM=datalad_osf
    - NOSE_OPTS=-s
    # Special settings/helper for combined coverage from special remotes execution
    - COVERAGE=coverage
    - DATALAD_DATASETS_TOPURL=http://datasets-tests.datalad.org
    # encrypted variables for testing against OSF
    - secure: XC8K0DOJh+XtyaQzj3RyKYbnHHwLf5wBqButuTq71O0uCTj3tMD4Vg3uFCvSD8E4hMJOrUCrWxQOTkCK1T6lsgQe6yAT9/CjBGrLKy9035QI7q+eCn+atGGQ9s+An+Q/zByQ6YlcytCGfu1LPIMEyFp0Uq57T7kSgJvpGx0SOsDs0naF3406DTAfTmQEr23thfKX6Wf8I6QBSeKPZnjh9r9k5BZVdcDZ7ZM/4JBOeDwyPIH+T8+51XtuzC3YEOdI1D12pz0B82eoefTsd28BVBKUC6VMOcSGPVzpZHn2fDLthBWEuZrVPsCMtzzB1/HofLb0E4Pdt7PHT+AF4/oM/8rcfeTrOaBZGeTue5luy4HMzpDNU3FdYESrbXRBB0rEl2Eg5M1DES5BHa0A/j4VJRLFhdr4SnQKTusZqDmZY//z7UT5Du/h2MUIScMDn1vK5oV7rNtCUr6KC9uEI0GhBXQR902ifWMAcEIhOrjO18qjyXlJVdgMLjt1K3hIL32CKCZ7OY7m8ckOgpez2bYIqhakRoGM7x4pc6nnxciUEUzNGkxneTTEUFedGsfYjqjaZ++7G2IEWWE+PYKCbD0nE611c03kQhTYxS/F8gLF8glo9G2Ce1kJrnQOE1sNkP/aHD1Y0ORcCA2lUuzOIQ51c+clrEweNFvapylljDsuQNU=
    - secure: qAjVGL7llItkscuzrfoeUDWXO7Axs23K5fOM1rrcMHo1eXw1EgYsFFPK4KAXdxxB8EPJAOIF5OoLEZwufGBTuvIe8QIdkakHwCwGCDqHQLN858qFdyW87zbfvFma9Abt2NF0/NIYwBo05nOODhpicMHvmCbT4D6D9e/rBsiufnXOVWebTO9qarMBS5XceJe07gD+1RkPQjh43TVqQQPWjK/rHoTfG+ciB/heTyNnY5AT7G31rlrdBc3DpAMl4pV6M07obVy0rFsTG2ucL6lPx8B5an5v42/tehhsgZPiFr0ZLQku4P7KuclvEHJMj2OD1IJdesrmDhdTzdwjBmKjISHANq8LM/pRsRSzZrQqawErrf++tOcrKdAAEHyJT5RFFHEf6ufevp2RYJwcnQyjJwC0bsOv1vFgp9v2hrwrLM8oyGDgX9DHDkerOXaVEaVfNyOOTWR+p7p87dHa4Ij4MMV2TDJeKuLholxWL3JyzXDrTXWZii8BDCNRKVwN1PkyPc65k7KVD6CTBbP0Lz9llI0lPnqOiFx4K29GEeYYw+Anb8s3AR+AWke4IZ0ki1hTkgWFSv96f9m8QsO0SKZPwtH7VGFAWayIQ6q5wFCziYMoxg/wvmPPtwwF/H76uBERKs0P4QJ3Q3QG4jXkw61V9IcjMcAlxVRPKENvylubUUA=
    - secure: DbkuAYEvEs8swgEpq52lza1/uczHQTJ8H9kqPwybT1gamEtioaARhUR6fbPDGgiJJxcIW+KoEHwqy9qb7bp7S5MJy/8KnEvu6psCdagn46W2ZdnEpWmEYG5alFkyfXRPZjSp3xeO4NpuxI+ks7Eek9aZgXfG1pdwk9fRRcdURNz/a+JOfuV+YQR6IPpvhVOqm5yOOMKWCvPmx/ldPdhhrWFfoZJR+/JSWxOID1i9W3GUmzISz91c519qlYHVXwzKtX9Imx9yRGyX3WlI8CyFKCTlH05ittlJFgRfjZlg1NMxQ9WVB89z8FoxXwkYZXP7fhQ2mF10x7GmCQ/YMdiVQsChmcO6GF/aAuVSc0FBD/+PivB8QTO1MESU+6Gs0Ou6okZ/zG070xc5dwks8OA/QHhsxQgcpFjxcrf2mtsU4ahdXEeWUGqFWKsTvsC/PaRbv1812HEB4htSBEVfjdjHK5Wo5vZs/Yz8AmouIIUIE791/Fquzk3LRDcri6MrW3IhIXX4Pc/0cctfLDEfhkhdIZtcjDYvShmUQTYuQizCjB7pE6e4XutjnyoMDREbmJ5h37JsepiLp4vshzK2Zarn9hWe6uqlSspFNBMKUJP5qLdiHnXIj19hznXuc1raW+0tnEOkJm5Uie4XvKQhBFSC0QhSGJLS+8Lwgb2XaCREbis=

before_install:
  # Just in case we need to check if nfs is there etc
  - sudo lsmod
  # The ultimate one-liner setup for NeuroDebian repository
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install eatmydata  # to speedup some installations

install:
  # Install standalone build of git-annex for the recent enough version
  - travis_retry sudo eatmydata apt-get install zip git-annex-standalone 
  # for metadata support
  - git config --global user.email "test@travis.land"
  - git config --global user.name "Travis Almighty"
  - cd ..; pip install -q codecov; cd -
  - pip install -r requirements-devel.txt
  # until a fixed osfclient is on pypi
  - pip install -r requirements.txt
  #- pip install 'sphinx>=1.6.2'
  # So we could test under sudo -E with PATH pointing to installed location
  - sudo sed -i -e 's/^Defaults.*secure_path.*$//' /etc/sudoers

script:
  # Verify that setup.py build doesn't puke
  - python setup.py build
  # Test installation system-wide
  - sudo pip install .
  - mkdir -p __testhome__
  - cd __testhome__
  # Report WTF information using system wide installed version
  - datalad wtf
  # Run tests
  - http_proxy=
    PATH=$PWD/tools/coverage-bin:$PATH
    $NOSE_WRAPPER `which nosetests` $NOSE_OPTS
      -v
      --with-doctest
      --with-coverage --cover-package datalad_osf
      --logging-level=INFO
      $TESTS_TO_PERFORM
  - cd ..

after_success:
  - coverage combine -a /tmp/.coverage-entrypoints-*
  - codecov
